name: Bundlewatch

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

env:
  FORCE_COLOR: 2
  NODE: 14

jobs:
  bundlewatch:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run dist
        run: npm run dist

      - name: Run bundlewatch
        uses: jackyef/bundlewatch-gh-action@0.2.0
        with:
          branch-base: main
          bundlewatch-config: .bundlewatch.config.json
          bundlewatch-github-token: "${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}"
